stages:
  - prepare
  - lint
  - build
#  - push
  - deploy

variables:
  CI_PROJECT_NAME: ella-admin-angular-fe
  DOMAIN: admin.ella.ronasit.com/admin
#  DOCKERFILE: ./Dockerfile
#  CHART_REPO: ronasit/static
#  CHART_VERSION: &ref "1.1.1"
#  DOCKER_CONTAINER_REGISTRY: gcr.io/ronas-it-development/${CI_PROJECT_NAME}-${CI_ENVIRONMENT_SLUG}

#include:
#  - project: 'k8s-tools/charts/static'
#    ref: *ref
#    file: '/helpers/.gitlab-ci-template.yml'

cache: &global_cache
  paths:
    - ./node_modules
  policy: pull

build_template: 
  stage: build
  image: node:14
  script:
    - npm run-script build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  tags:
    - docker
    - linux

node_dependencies:
  stage: prepare
  image: node:14
  script:
    - npm i
  tags:
    - docker
    - linux
  cache:
    <<: *global_cache
    policy: pull-push

tslint:
  stage: lint
  image: node:14
  script:
    - npm run-script lint
  tags:
    - docker
    - linux

#build_staging:
#  variables:
#    ENV: stg
#  <<: *build
#  except:
#    - production

#push:
#  extends: .push_gcr
#  environment:
#    name: "staging"
#  only:
#    - master

deploy_staging:
  stage: deploy 
  environment:
    name: "staging"
    url: https://${DOMAIN}
  image: projects.ronasit.com:4567/docker/ssh
  script:
   - rsync -av ./dist/ella-admin-angular-fe/ ec2-user@54.161.122.188:/var/www/ella.ronasit.com/
